### ISSUE TITLE
设备自动重启到Bootloader(即fastboot模式)

### ISSUE THREAD

**Issue by ItosEO** [OneB1ank/A1Memory#2]
**设备信息**
- 型号: iQOO9 (V2171)
- Soc: 骁龙8Gen1
- Android版本: 13
- OriginOS版本: PD2171_A_13.1.3.0.W10.V000L1 (OrginOS3)
- 
**A1内存管理配置**
- 全部遵循默认设置

**问题:**
开机一段时间后, 自动重启进入Bootloader .
A1内存管理日志无报错

**Comment by OneB1ank** [comment]
关闭hook lmkd
