### ISSUE TITLE
lsp附加模块安装失败

### ISSUE THREAD

**Issue by Seel6** [OneB1ank/A1Memory#4]
![Screenshot_2023-08-17-13-57-32-391_io github huskydg magisk](https://github.com/OneB1ank/A1Memory/assets/140370581/3cb88239-8853-4ce8-8693-fb6efc77db2e)

**Comment by OneB1ank** [comment]
拆包手动安装试试

**Comment by Seel6** [comment]
试过了也不可以 不过关闭r安装组件调用系统安装器可以安装成功或者重新mt签名一下也可以安装成功 可能是r安装组件的问题

**Comment by Seel6** [comment]
测出来了根本原因是Google play保护机制的问题关了之后什么都不做也可以用r安装安装成功并且beta16版本不会出现该问题 只有17全新安装的时候会出现连提示都没直接跳过![Screenshot_2023-08-17-18-00-13-703_com.android.vending.jpg](https://github.com/OneB1ank/A1Memory/assets/140370581/efc0192d-52e9-4b44-b79e-84aaecd7d0bd)
