### ISSUE TITLE
9.24（427）版本bug

### ISSUE THREAD

**Issue by Ryooen** [OneB1ank/A1Memory#5]
9.24（427）版本在小米13p的安卓14版本MIUI14.0.1.14上安装重启后卡第二屏，无限重启

**Comment by Ryooen** [comment]
大佬，刚更新的9.25版本仍然还是会第二屏，无限重启同样的安卓14版本MIUI14.0.1.14

**Comment by OneB1ank** [comment]
> 大佬，刚更新的9.25版本仍然还是会第二屏，无限重启同样的安卓14版本MIUI14.0.1.14

/data/adb/modules/Hc_memory/service.sh的23行，把||改成&&。明天会解决这个问题
