### ISSUE TITLE
A1需要重启手机来应用新设置吗？

### ISSUE THREAD

**Issue by Matthew-Harris-36** [OneB1ank/A1Memory#6]
![image](https://github.com/OneB1ank/A1Memory/assets/62049321/cd75494a-5516-4c01-b482-29441eb3fcfd)
我添加了几个白名单应用，A1需要重启手机来应用新配置吗？还是说默认就加载新配置了，不用重启手机。我在log里看不到相关信息。
10月5号的最新版A1

**Comment by OneB1ank** [comment]
终端面板有立即生效，也可以重启手机生效。Inotify检测文件变化实时生效配置文件暂时还没去写。
